### ISSUE TITLE
The Mail string Parsing error

### ISSUE THREAD

**Issue by zxc30314** [jcs090218/unity-verify-code#1]
![image](https://user-images.githubusercontent.com/31600998/160039038-345d4422-c974-44fc-bb2d-ab47d84a1d13.png)

**Comment by jcs090218** [comment]
Are you not able to get the verification code? 😕 Can you elaborate a bit more? Thanks!

**Comment by manisimbiwi** [comment]
> Are you not able to get the verification code? 😕 Can you elaborate a bit more? Thanks!

**Comment by zxc30314** [comment]
![image](https://user-images.githubusercontent.com/31600998/168198533-c9498e19-8a1e-46eb-94db-f87d96dda9ed.png)
Your code is "verification code is " at the beginning but Email is "Unity ID is"

**Comment by jcs090218** [comment]
The parser does not parse HTML directly. It only parses the text/plain content.

Here is the example data.

```
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Hello, 

Your Unity ID Security verification code is 728668 and will be expired in 5 minutes.

You are getting this email because we have noticed you are trying to log in via another geographic location. You can avoid these emails by adding a TFA system to your account by going to id.unity.com. 

For security purpose, please do not share your account information to anyone else and thanks for your understanding.
```

As you can see, the parse of the verification code is correct!

Hope this information helps! :)
