### ISSUE TITLE
Repository's permission

### ISSUE THREAD

**Issue by jcs090218** [jcs090218/unity-verify-code#3]
@webbertakken Do I have the permission to this repo? I think I am not able to write/change to this repo. Thanks!

**Comment by webbertakken** [comment]
You had write access, upgraded you to maintainer access.

Nobody can push directly to the main branch as it's protected. So all changes go through PRs.

**Comment by jcs090218** [comment]
Okay, got it!

Can you give me the permission to merge? I think it's limited to at least 1 approval.

**Comment by webbertakken** [comment]
Ah, just request all core contributors to review your PR. together we're online almost 24/7. 

Currently we've set up all repositories the same way. Even admins can't override the 1 approval rule. 
This way every code change is seen by more than 1 person. It works quite well I'd say,

**Comment by jcs090218** [comment]
Got it. I see. Thanks for answering my question! :)

**Comment by webbertakken** [comment]
You're very welcome :)
